name: deploy-nuxthub

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: setup-pnpm
        uses: pnpm/action-setup@v4
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: install-deps
        run: pnpm install
      - name: ensure-nuxthub
        run: pnpx nuxthub@latest ensure
      - name: build-app
        run: pnpm build
        env:
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}
          NUXT_PUBLIC_SITE_URL: ${{ vars.NUXT_PUBLIC_SITE_URL }}
      - name: deploy-nuxthub
        uses: nuxt-hub/action@v1
        id: deploy
        with:
          project-key: ${{ vars.NUXTHUB_PROJECT_KEY }}
